spring.application.name=event-booking
spring.data.mongodb.uri=mongodb://localhost:27017/collegeevents
spring.data.mongodb.database=collegeevents
server.port=8080

# JWT secret
jwt.secret=M3x9c25kZnM4cjcwOTgxMjM0NTY3ODkwYWJjZnsndsdnbdsGVmZ2hpag==

# Email (Brevo / Sendinblue)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=8fa3a3001@smtp-brevo.com
spring.mail.password=UmnBw6QJc3sXMaON
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Your sender details (used in EmailService)
app.email.sender.address=kamaleshrajan007@gmail.com
app.email.sender.name=SKCET EVENTS

# AWS S3 Configuration
